INSERT INTO Categories (CategoryName) VALUES ('Oleato');
INSERT INTO Categories (CategoryName) VALUES ('Hot Coffees');
INSERT INTO Categories (CategoryName) VALUES ('Hot Teas');
INSERT INTO Categories (CategoryName) VALUES ('Hot Drinks');
INSERT INTO Categories (CategoryName) VALUES ('Frappuccino');
INSERT INTO Categories (CategoryName) VALUES ('Cold Coffees');
INSERT INTO Categories (CategoryName) VALUES ('Iced Teas');
INSERT INTO Categories (CategoryName) VALUES ('Cold Drinks');
INSERT INTO Categories (CategoryName) VALUES ('Coffee Travellers');
INSERT INTO Categories (CategoryName) VALUES ('Packaged Beverages');